### ISSUE TITLE
TypeError when number of processes exceeds resolvers. 

### ISSUE THREAD

**Issue by gerry** [TheRook/subbrute#15]
While running some tests using a small number of internal resolvers, I ran into this exception. 

(a slightly sanitized traceback)
```
Process lookup-4:
Traceback (most recent call last):
  File "/opt/xxx/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "subbrute.py", line 278, in run
    addrs = self.check(test_domain)
  File "subbrute.py", line 247, in check
    raise e
TypeError: coercing to Unicode: need string or buffer, bool found
```

This patch seemed to make it go away, not sure it's the correct fix though.
```diff
diff --git a/subbrute.py b/subbrute.py
index 2faba8c..feee3bd 100644
--- a/subbrute.py
+++ b/subbrute.py
@@ -241,6 +241,10 @@ class lookup(multiprocessing.Process):
                     #Some old versions of dnspython throw this error,
                     #doesn't seem to affect the results,  and it was fixed in later versions.
                     pass
+                elif type(e) == TypeError:
+                    # We'll get here if the number procs > number of resolvers.
+                    self.in_q.put(host)
+                    return False
                 else:
                     trace("Problem processing host:", host)
                     #dnspython threw some strange exception...
```

**Comment by TheRook** [comment]
I think this change looks good,  do you mind submitting a pull request?

**Comment by gerry** [comment]
Sent!

**Comment by TheRook** [comment]
Patch merged.
