### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by MythHack** [TheRook/subbrute#19]
usage -c 20

Exception in thread Thread-10:
Traceback (most recent call last):
  File "c:\python\32-bit\3.4\lib\threading.py", line 921, in _bootstrap_inner
  File "subbrute.py", line 333, in run
  File "subbrute.py", line 298, in check
  File "subbrute.py", line 226, in check
  File "C:\Python34\lib\site-packages\dns\resolver.py", line 774, in query
  File "C:\Python34\lib\site-packages\dns\name.py", line 613, in from_text
dns.name.EmptyLabel

**Comment by TheRook** [comment]
I have run subbrute -c 100 or more. What other arguments did you pass in?

**Comment by MythHack** [comment]
First, I'm sorry my English is poor. I can only be accomplished through the exchange of google translate. : (

subbrute -c 20 -a -s all1.txt -o test.txt test.com 

My dictionary is my own which has 899kb

**Comment by TheRook** [comment]
1) Make sure you are fully updated `git puill`
2) Do you get the same error with:
subbrute -c 20 -a -o test.txt test.com

all1.txt may be malformed...

**Comment by MythHack** [comment]
Ok I try~thx

**Comment by TheRook** [comment]
I think this was an input error.  I'm happy to add more input validation,  but I'm not exactly sure how the file was malformed.  We will do some more UTF8 testing to support the new charsets approved by ICANN.
